[package]
name = "suilend"
version = "0.0.1"
published-at = "0xa81dad144b39b6bfe8491d593136d0d2e21d308339990c23fa63275c28b43e86"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true
 
[dependencies.Pyth]
git = "https://github.com/0xripleys/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "7e72f2754ffdb9138ac2d9ba11a014e7638132f2"

[addresses]
sui = "0x2"
suilend = "0x0"
pyth = "0x8d97f1cd6ac663735be08d1d2b6d02a159e711586461306ce60a2b7a6a565a9e"
